LIB_SRC = 			\
	Acceptor.cc		\
	Channel.cc		\
	EventLoop.cc		\
	EventLoopThread.cc	\
	InetAddress.cc		\
	Poller.cc		\
	Socket.cc		\
	SocketsOps.cc		\
	Timer.cc		\
	TimerQueue.cc

BINARIES = test1 test2 test3 test4 test5 test6 test7

all: $(BINARIES)

include ../reactor_lib.mk

test1: test1.cc
test2: test2.cc
test3: test3.cc
test4: test4.cc
test5: test5.cc
test6: test6.cc
test7: test7.cc
