LIB_SRC = Channel.cc EventLoop.cc Poller.cc Timer.cc TimerQueue.cc
BINARIES = test1 test2 test3 test4

all: $(BINARIES)

include ../reactor.mk

test1: test1.cc
test2: test2.cc
test3: test3.cc
test4: test4.cc
