workspace(name = "com_chenshuo_recipes_topk")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# abseil
http_archive(
    name = "absl",
    strip_prefix = "abseil-cpp-master",
    urls = ["https://github.com/abseil/abseil-cpp/archive/master.zip"],
)

# muduo
http_archive(
    name = "muduo",
    strip_prefix = "muduo-master",
    urls = ["https://github.com/chenshuo/muduo/archive/master.zip"],
)
