// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sudoku.proto

package sudoku;

public final class Sudoku {
  private Sudoku() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SudokuRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string checkerboard = 1;
    boolean hasCheckerboard();
    String getCheckerboard();
  }
  public static final class SudokuRequest extends
      com.google.protobuf.GeneratedMessage
      implements SudokuRequestOrBuilder {
    // Use SudokuRequest.newBuilder() to construct.
    private SudokuRequest(Builder builder) {
      super(builder);
    }
    private SudokuRequest(boolean noInit) {}
    
    private static final SudokuRequest defaultInstance;
    public static SudokuRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public SudokuRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sudoku.Sudoku.internal_static_sudoku_SudokuRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sudoku.Sudoku.internal_static_sudoku_SudokuRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string checkerboard = 1;
    public static final int CHECKERBOARD_FIELD_NUMBER = 1;
    private java.lang.Object checkerboard_;
    public boolean hasCheckerboard() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getCheckerboard() {
      java.lang.Object ref = checkerboard_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          checkerboard_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCheckerboardBytes() {
      java.lang.Object ref = checkerboard_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        checkerboard_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      checkerboard_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasCheckerboard()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCheckerboardBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCheckerboardBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static sudoku.Sudoku.SudokuRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sudoku.Sudoku.SudokuRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sudoku.Sudoku.SudokuRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sudoku.Sudoku.SudokuRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sudoku.Sudoku.SudokuRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sudoku.Sudoku.SudokuRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static sudoku.Sudoku.SudokuRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sudoku.Sudoku.SudokuRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sudoku.Sudoku.SudokuRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sudoku.Sudoku.SudokuRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sudoku.Sudoku.SudokuRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements sudoku.Sudoku.SudokuRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sudoku.Sudoku.internal_static_sudoku_SudokuRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sudoku.Sudoku.internal_static_sudoku_SudokuRequest_fieldAccessorTable;
      }
      
      // Construct using sudoku.Sudoku.SudokuRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        checkerboard_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sudoku.Sudoku.SudokuRequest.getDescriptor();
      }
      
      public sudoku.Sudoku.SudokuRequest getDefaultInstanceForType() {
        return sudoku.Sudoku.SudokuRequest.getDefaultInstance();
      }
      
      public sudoku.Sudoku.SudokuRequest build() {
        sudoku.Sudoku.SudokuRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private sudoku.Sudoku.SudokuRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        sudoku.Sudoku.SudokuRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public sudoku.Sudoku.SudokuRequest buildPartial() {
        sudoku.Sudoku.SudokuRequest result = new sudoku.Sudoku.SudokuRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.checkerboard_ = checkerboard_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sudoku.Sudoku.SudokuRequest) {
          return mergeFrom((sudoku.Sudoku.SudokuRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(sudoku.Sudoku.SudokuRequest other) {
        if (other == sudoku.Sudoku.SudokuRequest.getDefaultInstance()) return this;
        if (other.hasCheckerboard()) {
          setCheckerboard(other.getCheckerboard());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasCheckerboard()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              checkerboard_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string checkerboard = 1;
      private java.lang.Object checkerboard_ = "";
      public boolean hasCheckerboard() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getCheckerboard() {
        java.lang.Object ref = checkerboard_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          checkerboard_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCheckerboard(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        checkerboard_ = value;
        onChanged();
        return this;
      }
      public Builder clearCheckerboard() {
        bitField0_ = (bitField0_ & ~0x00000001);
        checkerboard_ = getDefaultInstance().getCheckerboard();
        onChanged();
        return this;
      }
      void setCheckerboard(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        checkerboard_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:sudoku.SudokuRequest)
    }
    
    static {
      defaultInstance = new SudokuRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:sudoku.SudokuRequest)
  }
  
  public interface SudokuResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional bool solved = 1 [default = false];
    boolean hasSolved();
    boolean getSolved();
    
    // optional string checkerboard = 2;
    boolean hasCheckerboard();
    String getCheckerboard();
  }
  public static final class SudokuResponse extends
      com.google.protobuf.GeneratedMessage
      implements SudokuResponseOrBuilder {
    // Use SudokuResponse.newBuilder() to construct.
    private SudokuResponse(Builder builder) {
      super(builder);
    }
    private SudokuResponse(boolean noInit) {}
    
    private static final SudokuResponse defaultInstance;
    public static SudokuResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public SudokuResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sudoku.Sudoku.internal_static_sudoku_SudokuResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sudoku.Sudoku.internal_static_sudoku_SudokuResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional bool solved = 1 [default = false];
    public static final int SOLVED_FIELD_NUMBER = 1;
    private boolean solved_;
    public boolean hasSolved() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public boolean getSolved() {
      return solved_;
    }
    
    // optional string checkerboard = 2;
    public static final int CHECKERBOARD_FIELD_NUMBER = 2;
    private java.lang.Object checkerboard_;
    public boolean hasCheckerboard() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getCheckerboard() {
      java.lang.Object ref = checkerboard_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          checkerboard_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCheckerboardBytes() {
      java.lang.Object ref = checkerboard_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        checkerboard_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      solved_ = false;
      checkerboard_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, solved_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCheckerboardBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, solved_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCheckerboardBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static sudoku.Sudoku.SudokuResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sudoku.Sudoku.SudokuResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sudoku.Sudoku.SudokuResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sudoku.Sudoku.SudokuResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sudoku.Sudoku.SudokuResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sudoku.Sudoku.SudokuResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static sudoku.Sudoku.SudokuResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sudoku.Sudoku.SudokuResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sudoku.Sudoku.SudokuResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sudoku.Sudoku.SudokuResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sudoku.Sudoku.SudokuResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements sudoku.Sudoku.SudokuResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sudoku.Sudoku.internal_static_sudoku_SudokuResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sudoku.Sudoku.internal_static_sudoku_SudokuResponse_fieldAccessorTable;
      }
      
      // Construct using sudoku.Sudoku.SudokuResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        solved_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        checkerboard_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sudoku.Sudoku.SudokuResponse.getDescriptor();
      }
      
      public sudoku.Sudoku.SudokuResponse getDefaultInstanceForType() {
        return sudoku.Sudoku.SudokuResponse.getDefaultInstance();
      }
      
      public sudoku.Sudoku.SudokuResponse build() {
        sudoku.Sudoku.SudokuResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private sudoku.Sudoku.SudokuResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        sudoku.Sudoku.SudokuResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public sudoku.Sudoku.SudokuResponse buildPartial() {
        sudoku.Sudoku.SudokuResponse result = new sudoku.Sudoku.SudokuResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.solved_ = solved_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.checkerboard_ = checkerboard_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sudoku.Sudoku.SudokuResponse) {
          return mergeFrom((sudoku.Sudoku.SudokuResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(sudoku.Sudoku.SudokuResponse other) {
        if (other == sudoku.Sudoku.SudokuResponse.getDefaultInstance()) return this;
        if (other.hasSolved()) {
          setSolved(other.getSolved());
        }
        if (other.hasCheckerboard()) {
          setCheckerboard(other.getCheckerboard());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              solved_ = input.readBool();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              checkerboard_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional bool solved = 1 [default = false];
      private boolean solved_ ;
      public boolean hasSolved() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public boolean getSolved() {
        return solved_;
      }
      public Builder setSolved(boolean value) {
        bitField0_ |= 0x00000001;
        solved_ = value;
        onChanged();
        return this;
      }
      public Builder clearSolved() {
        bitField0_ = (bitField0_ & ~0x00000001);
        solved_ = false;
        onChanged();
        return this;
      }
      
      // optional string checkerboard = 2;
      private java.lang.Object checkerboard_ = "";
      public boolean hasCheckerboard() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getCheckerboard() {
        java.lang.Object ref = checkerboard_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          checkerboard_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCheckerboard(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        checkerboard_ = value;
        onChanged();
        return this;
      }
      public Builder clearCheckerboard() {
        bitField0_ = (bitField0_ & ~0x00000002);
        checkerboard_ = getDefaultInstance().getCheckerboard();
        onChanged();
        return this;
      }
      void setCheckerboard(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        checkerboard_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:sudoku.SudokuResponse)
    }
    
    static {
      defaultInstance = new SudokuResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:sudoku.SudokuResponse)
  }
  
  public static abstract class SudokuService
      implements com.google.protobuf.Service {
    protected SudokuService() {}
    
    public interface Interface {
      public abstract void solve(
          com.google.protobuf.RpcController controller,
          sudoku.Sudoku.SudokuRequest request,
          com.google.protobuf.RpcCallback<sudoku.Sudoku.SudokuResponse> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new SudokuService() {
        @java.lang.Override
        public  void solve(
            com.google.protobuf.RpcController controller,
            sudoku.Sudoku.SudokuRequest request,
            com.google.protobuf.RpcCallback<sudoku.Sudoku.SudokuResponse> done) {
          impl.solve(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.solve(controller, (sudoku.Sudoku.SudokuRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return sudoku.Sudoku.SudokuRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return sudoku.Sudoku.SudokuResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void solve(
        com.google.protobuf.RpcController controller,
        sudoku.Sudoku.SudokuRequest request,
        com.google.protobuf.RpcCallback<sudoku.Sudoku.SudokuResponse> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return sudoku.Sudoku.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.solve(controller, (sudoku.Sudoku.SudokuRequest)request,
            com.google.protobuf.RpcUtil.<sudoku.Sudoku.SudokuResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return sudoku.Sudoku.SudokuRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return sudoku.Sudoku.SudokuResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends sudoku.Sudoku.SudokuService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void solve(
          com.google.protobuf.RpcController controller,
          sudoku.Sudoku.SudokuRequest request,
          com.google.protobuf.RpcCallback<sudoku.Sudoku.SudokuResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          sudoku.Sudoku.SudokuResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            sudoku.Sudoku.SudokuResponse.class,
            sudoku.Sudoku.SudokuResponse.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public sudoku.Sudoku.SudokuResponse solve(
          com.google.protobuf.RpcController controller,
          sudoku.Sudoku.SudokuRequest request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public sudoku.Sudoku.SudokuResponse solve(
          com.google.protobuf.RpcController controller,
          sudoku.Sudoku.SudokuRequest request)
          throws com.google.protobuf.ServiceException {
        return (sudoku.Sudoku.SudokuResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          sudoku.Sudoku.SudokuResponse.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sudoku_SudokuRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sudoku_SudokuRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sudoku_SudokuResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sudoku_SudokuResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014sudoku.proto\022\006sudoku\"%\n\rSudokuRequest\022" +
      "\024\n\014checkerboard\030\001 \002(\t\"=\n\016SudokuResponse\022" +
      "\025\n\006solved\030\001 \001(\010:\005false\022\024\n\014checkerboard\030\002" +
      " \001(\t2G\n\rSudokuService\0226\n\005Solve\022\025.sudoku." +
      "SudokuRequest\032\026.sudoku.SudokuResponseB\t\200" +
      "\001\001\210\001\001\220\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_sudoku_SudokuRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_sudoku_SudokuRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sudoku_SudokuRequest_descriptor,
              new java.lang.String[] { "Checkerboard", },
              sudoku.Sudoku.SudokuRequest.class,
              sudoku.Sudoku.SudokuRequest.Builder.class);
          internal_static_sudoku_SudokuResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_sudoku_SudokuResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sudoku_SudokuResponse_descriptor,
              new java.lang.String[] { "Solved", "Checkerboard", },
              sudoku.Sudoku.SudokuResponse.class,
              sudoku.Sudoku.SudokuResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
